export const contactEN = {
  sectionLabel: "Contact",
  heading: "Get in",
  headingAccent: "Touch",
  body: "Interested in joining B401, collaborating on research, or learning more about our programs? Reach out to us.",
  locationLabel: "Location",
  locationValue: "TW2-901 Room, Tower 2 Building\nInstitut Teknologi Sepuluh Nopember\nSurabaya, Indonesia",
  emailLabel: "Email",
  emailValue: "b401robotics@gmail.com",
  hoursLabel: "Office Hours",
  hoursValue: "Monday – Friday\n08:00 – 17:00 WIB",
  formTitle: "Send a Message",
  nameLabel: "Full Name",
  namePlaceholder: "Your name",
  emailFormLabel: "Email Address",
  emailPlaceholder: "your@email.com",
  subjectLabel: "Subject",
  subjectPlaceholder: "How can we help?",
  messageLabel: "Message",
  messagePlaceholder: "Tell us more...",
  sendBtn: "Send Message",
} as const;
