export const contactID = {
  sectionLabel: "Kontak",
  heading: "Hubungi",
  headingAccent: "Kami",
  body: "Tertarik bergabung dengan B401, berkolaborasi dalam penelitian, atau ingin mengetahui lebih lanjut tentang program kami? Hubungi kami.",
  locationLabel: "Lokasi",
  locationValue: "Ruang TW2-901, Gedung Tower\nInstitut Teknologi Sepuluh Nopember\nSurabaya, Indonesia",
  emailLabel: "Email",
  emailValue: "b401robotics@gmail.com",
  hoursLabel: "Jam Operasional",
  hoursValue: "Senin – Jumat\n08:00 – 17:00 WIB",
  formTitle: "Kirim Pesan",
  nameLabel: "Nama Lengkap",
  namePlaceholder: "Nama Anda",
  emailFormLabel: "Alamat Email",
  emailPlaceholder: "email@anda.com",
  subjectLabel: "Subjek",
  subjectPlaceholder: "Ada yang bisa kami bantu?",
  messageLabel: "Pesan",
  messagePlaceholder: "Ceritakan lebih lanjut...",
  sendBtn: "Kirim Pesan",
} as const;
