export const practicumsEN = {
  sectionLabel: "Practicums",
  heading: "Structured",
  headingAccent: "Learning",
  body: "Our practicum program is designed to complement theoretical coursework with hands-on, real-world engineering experience.",
  sessions: "sessions",
  items: [
    {
      code: "P01",
      title: "Introduction to Robotics",
      desc: "Fundamentals of robotic systems, kinematics, coordinate frames, and basic programming of robotic arms.",
      sessions: "12",
      level: "Beginner",
      topics: ["Robot kinematics", "Coordinate transforms", "Basic actuation"],
    },
    {
      code: "P02",
      title: "Embedded Systems Programming",
      desc: "Hardware interfacing, microcontroller programming, real-time operating systems, and peripheral communication protocols.",
      sessions: "10",
      level: "Intermediate",
      topics: ["Microcontrollers", "RTOS", "I2C / SPI / UART"],
    },
    {
      code: "P03",
      title: "Computer Vision & Image Processing",
      desc: "Image acquisition, filtering, feature extraction, object detection, and deep learning-based vision systems.",
      sessions: "10",
      level: "Intermediate",
      topics: ["OpenCV", "Feature detection", "CNN / YOLO"],
    },
    {
      code: "P04",
      title: "Control Systems Design",
      desc: "System modeling, stability analysis, PID tuning, and implementation of advanced control strategies.",
      sessions: "8",
      level: "Advanced",
      topics: ["PID control", "State-space", "Frequency response"],
    },
    {
      code: "P05",
      title: "Autonomous Navigation",
      desc: "SLAM algorithms, localization, path planning, and deployment on mobile robotic platforms.",
      sessions: "12",
      level: "Advanced",
      topics: ["SLAM", "ROS 2", "Path planning"],
    },
  ],
} as const;
