export const practicumsID = {
  sectionLabel: "Praktikum",
  heading: "Pembelajaran",
  headingAccent: "Terstruktur",
  body: "Program praktikum kami dirancang untuk melengkapi perkuliahan teoritis dengan pengalaman rekayasa langsung di dunia nyata.",
  sessions: "sesi",
  items: [
    {
      code: "P01",
      title: "Pengantar Robotika",
      desc: "Dasar-dasar sistem robotik, kinematika, kerangka koordinat, dan pemrograman dasar lengan robot.",
      sessions: "12",
      level: "Pemula",
      topics: ["Kinematika robot", "Transformasi koordinat", "Aktuasi dasar"],
    },
    {
      code: "P02",
      title: "Pemrograman Sistem Tertanam",
      desc: "Antarmuka perangkat keras, pemrograman mikrokontroler, sistem operasi real-time, dan protokol komunikasi periferal.",
      sessions: "10",
      level: "Menengah",
      topics: ["Mikrokontroler", "RTOS", "I2C / SPI / UART"],
    },
    {
      code: "P03",
      title: "Visi Komputer & Pengolahan Citra",
      desc: "Akuisisi citra, pemfilteran, ekstraksi fitur, deteksi objek, dan sistem visi berbasis deep learning.",
      sessions: "10",
      level: "Menengah",
      topics: ["OpenCV", "Deteksi fitur", "CNN / YOLO"],
    },
    {
      code: "P04",
      title: "Perancangan Sistem Kendali",
      desc: "Pemodelan sistem, analisis kestabilan, penalaan PID, dan implementasi strategi kendali tingkat lanjut.",
      sessions: "8",
      level: "Lanjutan",
      topics: ["Kendali PID", "Ruang keadaan", "Respons frekuensi"],
    },
    {
      code: "P05",
      title: "Navigasi Otonom",
      desc: "Algoritma SLAM, lokalisasi, perencanaan jalur, dan penerapan pada platform robot bergerak.",
      sessions: "12",
      level: "Lanjutan",
      topics: ["SLAM", "ROS 2", "Perencanaan jalur"],
    },
  ],
} as const;
